# Generated by Django 5.1.5 on 2025-01-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_name', models.CharField(blank=True, help_text='enter the employee name', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField(null=True)),
                ('emp_gender', models.CharField(max_length=20, null=True)),
                ('emp_contact', models.CharField(max_length=15, null=True)),
                ('emp_email', models.EmailField(max_length=254, null=True)),
                ('emp_address', models.TextField(null=True)),
                ('emp_department', models.CharField(max_length=100, null=True)),
                ('emp_jobtitle', models.CharField(max_length=100, null=True)),
                ('emp_link', models.URLField(help_text='LinkedIn or LeetCode profile', null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('emp_salary', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
